config/routes.rb
Rails.application.routes.draw do
  root 'toppeges#index'
  get 'concepts/index'
  get 'menus/index'
  get 'accesses/index'
  get 'recruits/index'
  get 'news/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController
end

app/controllers/toppeges_controller.rb
class ToppegesController < ApplicationController
  def index
  end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/toppeges_helper.rb
module ToppegesHelper
end

app/views/accesses/index.html.erb
<div class="accesses-new-wrapper">
  <div class="container  text-white">
     <div class="display-4 text-center">Access</div>
    <div class="accesses-row col-md-6 offset-md-3 text-center">
        <small>〒480-0146<br>
               愛知県丹羽郡大口町余野3-103<br>
               メゾンミズノ101<br>
               TEL 0587-96-9086<br>
               <br>
               自転車置き場・駐車場完備
               道路沿いに看板があります。
        </small>
    </div>
    <div class="map-row col-md-6 offset-md-3">
      <div class="embed-responsive embed-responsive-4by3">
       <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6508.710260811267!2d136.914154!3d35.346832!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60030c106ee9ac5d%3A0xa7f9e6cb495582ae!2z77yo77yh77ys77yv772B772O772E44O7772W772J772W772P!5e0!3m2!1sja!2sjp!4v1588941855439!5m2!1sja!2sjp" 
                    width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>          
      </div>
    </div>  
  </div>
</div>    

app/views/concepts/index.html.erb
<div class="concepts-new-wrapper">
  <div class="container text-white">
    <div class="display-4 text-center">Concept</div>
　　<div class="row col-md-6 offset-md-3  text-white">
     <span><%= image_tag "11.png", class:"concepts-phote img-fluid "%></span>
    </div>
    <h3 class="concepts text-md-center col-md-10 offset-md-1">〜ヘアースタイルを通して毎日をより輝やく毎日へ〜</h3>
    <div class="concepts-row col-md-10 offset-md-1 text-md-center">
       <h4 class="text-md-center">HALOandvivo とは？</h4>
       <br>
      　　後光・光輪・光
       <br>　
       <br>
          HALOから光が溢れ出し、あなたをそっと照らし続けられる場所
       <br>
          朝、学校・仕事にいく前、デートや大切な人と会う時<br>
       <br>
          ヘアースタイルがキレイでバッチリ決まったら<br>
          自分に自信がつき、１日の始まりが素敵になる。<br>
       <br>
          気分が変わる事で見るもの・聴くもの・感じるものが<br>
          よりキラキラと輝き毎日が楽しくなる。<br>
        <br>
          HALOはヘアースアイルにはそんな力があると信じています。
        <br>
          お客様が、何を望んでいるのか、どんな自分になりたいのか<br>
          真剣に耳を傾け技術・サービスを全力でご提供していきます。<br>
    </div>
  </div>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <body>
    <header class="header">
      <nav class="navbar navbar-expand-sm navbar-dark bg-white mt-3 mb-3">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
         <span class="navbar-toggler-icon"></span>
        </button>
        <span class="navbar-brand"><%= image_tag "helo.png"%></span>
        <div class="collapse navbar-collapse " id="Navber">
           <ul class="navbar-nav mr-auto">
               <li class="nav-item active"><%= link_to "Home", root_path, class:"p-2 text-dark "%></li>
               <li class="nav-item"><%= link_to "Concept", concepts_index_path, class:"p-2 text-dark"%></li>
               <li class="nav-item"><%= link_to "Menu", menus_index_path, class:"p-2 text-dark" %></li>
               <li class="nav-item"><%= link_to "Access", accesses_index_path, class:"p-2 text-dark" %></li>
               <li class="nav-item"><%= link_to "NEWs", news_index_path, class:"p-2 text-dark"%></li>
               <li class="nav-item"><%= link_to "Recruit", recruits_index_path, class:"p-2 text-dark"%></li>
           </ul>
        </div>
      </nav> 
    </header>
    <footer class="footer" >
      <div class="d-flex flex-column align-items-center p-3 px-md-4  bg-white border-bottom shadow-sm fixed-bottom text-center">
       <span><%= image_tag "helo.png", class: "footer-navbar-brand " %>
		      <small class="text-muted">© 2020</small>
		   </span>
    <!--    <div class="address">
         <span><%= image_tag "helo.png", class: "footer-navbar-brand" %></span>
          <small>〒480-0146　愛知県丹羽郡大口町余野3-103 メゾンミズノ101 TEL 0587-96-9086</small>
        </div>-->
      </div>  
    </footer> 
   </body> 
    <%= yield %>
</html>

app/views/menus/index.html.erb
<div class="menus-new-wrapper">
  <div class="container text-white">
　  <div class="display-4 text-center">Menu</div>　      
    <div class="menus-row text-white">
      <u><h3>CUT（シャンプー・スタイリング込）</h3></u>
      <table>
        <tr>
          <td>一般</td><td>¥4,500</td>
        </tr>
         <tr>
          <td>高校生</td><td>¥3,000</td>
        </tr>
         <tr>
          <td>中学生</td><td>¥2,800</td>
        </tr>
         <tr>
          <td>小学生以下</td><td>¥2,500</td>
        </tr>
         <tr>
          <td>一般</td><td>¥4,500</td>
        </tr>  
      </table>
    </div>
    <div class="menus-row text-white">
     <u><h3>COLOR（カット・シャンプー・スタイリング別）</h3></u>
      <table>
        <tr>
          <td>カラーS</td><td>¥4,500</td>
        </tr>
         <tr>
          <td>カラーM</td><td>¥5,000</td>
        </tr>
         <tr>
          <td>カラーL　(LL＋500円)</td><td>¥6,000</td>
        </tr>
         <tr>
          <td>リタッチカラー　(45日以内ご来店)</td><td>¥3,500</td>
        </tr>
      </table>
    </div>  
    <div class="menus-row text-white">
      <u><h3>PERM</h3></u>
      <table>
        <tr>
          <td>ナチュラルパーマ</td><td>¥8,500~</td>
        </tr>
         <tr>
          <td>ピンパーマ</td><td>¥8,500~</td>
        </tr>
         <tr>
          <td>デザインパーマ</td><td>¥10,000~</td>
        </tr>
         <tr>
          <td>デザインコスメパーマ</td><td>¥12,000~</td>
        </tr>
        <tr>
          <td>ストレートパーマ（ニュアンス・パーマ落とし</td><td>¥10,000~</td>
        </tr>
        <tr>
          <td>縮毛矯正</td><td>¥15,000~</td>
        </tr>
      </table>
      <h6>カット・シャンプー・スタイリング込長さ・デザインにより料金が異なります</h6>
    </div> 
    <div class="menus-row text-white">
      <u><h3>TREATMENT（シャンプー・スタイリング別）</h3></u>
      <table>
        <tr>
          <td>トリートメント</td><td>¥1,500~</td>
        </tr>
         <tr>
          <td>クイックスキャルプケア</td><td>¥800</td>
        </tr>
         <tr>
          <td>ヘッドスパ</td><td>¥5,000</td>
        </tr>
      </table>
    </div>  
    <div class="menus-row text-white">
      <u><h3>OTHERS</h3></u>
      <table>
        <tr>
          <td>セット</td><td>¥4,000~</td>
        </tr>
        <tr>
          <td>シャンプー・ブロー</td><td>¥3,000</td>
        </tr>
        <tr>
          <td>シャンプー・ドライ</td><td>¥1,500</td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/news/index.html.erb
<div class="news-new-wrapper">
  <div class="container text-white">
     <div class="display-4 text-center">News</div>
    <div class="row">
     <div class=col-md-5>
       <h1>只今作成中</h1>
     </div>   
    </div>
  </div>
</div>

app/views/recruits/index.html.erb
<div class="recruits-new-wrapper">
  <div class="container text-white">
     <div class="display-4 text-center">Recruit</div>
    <div class="row recruits-row ">
        <div class="col-md-6">
          <%= image_tag "22.png", class:"recruits-phote img-fluid "%>
        </div>
        <div class="recruits  col-md-6 text-center">
         <h2>只今、募集はしておりません</h2>  
         <h3>お問い合わせ</h3>
          <small>HALO andvivo<br>
                 tel 0587-96-9086<br>
                 担当　イノウエ
          </small>
        </div> 
    </div>
  </div>
</div>

app/views/toppeges/index.html.erb
<div class="container top-hero-wrapper">
  <div class="row">
     <div class="card-img col-md-12">
        <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
           <div class="carousel-item active" data-interval="50">
             <span><%= image_tag "02.png", class:"navbar-img img-fluid" %></span>
           </div>
           <div class="carousel-item " data-interval="50">
             <span><%= image_tag "55.png", class:"navbar-img img-fluid" %></span>
           </div>
           <div class="carousel-item" data-interval="50">
            <span><%= image_tag "22.png", class:"navbar-img img-fluid" %></span>
           </div>
           <div class="carousel-item" data-interval="50">
            <span><%= image_tag "15.png", class:"navbar-img img-fluid"%></span>
           </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
           <span class="sr-only">前へ</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
           <span class="carousel-control-next-icon" aria-hidden="true"></span>
           <span class="sr-only">次へ</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</div> 